In [21]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifier, Lasso
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
df = pd.read_csv('Iris.csv')

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
df = df.drop('Id', axis= 1)

In [6]:
df.Species = df.Species.map({'Iris-setosa': 0,
                             'Iris-versicolor': 1,
                             'Iris-virginica': 2})

In [43]:
X = df.drop(['Species'], axis= 1).values
y = df.Species.values

In [44]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state= 10, stratify= y)

In [45]:
rfc= LogisticRegression(max_iter=1000)

In [46]:
rfc.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [47]:
pred= rfc.predict(X)

In [48]:
from sklearn.metrics import f1_score, classification_report

In [49]:
f1_score(y, pred, average='macro')

0.9866613311991462

In [50]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      0.96      0.98        50
           2       0.96      1.00      0.98        50

    accuracy                           0.99       150
   macro avg       0.99      0.99      0.99       150
weighted avg       0.99      0.99      0.99       150



In [53]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [54]:
X_test

array([[1],
       [2],
       [3],
       [4]])

In [66]:
a = 1
b = 2
c = 3
d = 3
config = [[a,b,c,d]]

In [67]:
config

[[1, 2, 3, 3]]

In [68]:
X_test = config

In [69]:
rfc.predict(X_test)

array([0], dtype=int64)

In [15]:
import pickle
# open a file, where you ant to store the data
file = open('iris_linear.pkl', 'wb')

# dump information to that file
pickle.dump(rfc, file)

In [16]:
with open('iris_lin.bin', 'wb') as f_out:
    pickle.dump(rfc, f_out)
    f_out.close()

In [17]:
df.head(2)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0

In [21]:
config = {'SepalLengthCm': [3,4,5],
          'SepalWidthCm': [4,5,6],
          'PetalLengthCm': [1,2,3]}

In [ ]:
config.

In [22]:
import requests

url = 'http://192.168.1.11:9696/'
r= requests.post(url, json= config)
r.text.strip()

'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"\n  "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n  <head>\n    <title>ValueError: Expected 2D array, got scalar array instead:\narray={&#x27;SepalLengthCm&#x27;: [3, 4], &#x27;SepalWidthCm&#x27;: [4, 5], &#x27;PetalLengthCm&#x27;: [1, 3]}.\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample. // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"\n        type="text/css">\n    <!-- We need to make sure this has a favicon so that the debugger does\n         not accidentally trigger a request to /favicon.ico which might\n         change the application\'s state. -->\n    <link rel="shortcut icon"\n        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">\n    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>\n    <script type="text/javasc

In [63]:
def create_model(config):
    X = df.drop(['Species'], axis= 1).values
    y = df.Species.values

    model = LogisticRegression(max_iter=1000)
    model.fit(X, y)

    X_test=config
    return model.predict(X_test)

In [64]:
create_model(config)

array([2], dtype=int64)